### ISSUE TITLE
[SUPPORT] Theme changes

### ISSUE THREAD

**Issue by oliveiraev** [zagortenay333/numix-cinnamon#20]
How do I strip off the dark line on 'panel-top'?

I used to put the same color on both ```<rect />'s``` at panel-top.svg with Cinnamon 2. versions.

Now, on Cinnamon 3 it doesn't affect anything.

Clarifying, I want this:

![image](https://cloud.githubusercontent.com/assets/320460/22517509/7681edb8-e890-11e6-9f61-cacfd51381bf.png)

become this:

![image](https://cloud.githubusercontent.com/assets/320460/22517666/16b75ba6-e891-11e6-8180-2b8cf85488fd.png)

Thanks in any advice.

**Comment by zagortenay333** [comment]
That can't be done from within the cinnamon theme alone. Not without removing the border from the panel's svg image outright.

One thing you could do is to install the **transparent panels** extension. That extension adds a css class to the cinnamon theme `.panel-transparent` that you can use to override the panel when a window gets tiled.

So add this to the `cinnamon.css` file:
```css
/* top */
.panel-top.panel-transparent {
    border-image: url(use_custom_panel) 8;
    /* or something else */
}
/* bottom */
.panel-bottom.panel-transparent {
    border-image: url(use_custom_panel) 8;
    /* or something else */
}
/* left */
.panel-left.panel-transparent {
    border-image: url(use_custom_panel) 8;
    /* or something else */
}
/* right */
.panel-right.panel-transparent {
    border-image: url(use_custom_panel) 8;
    /* or something else */
}
```

...and in the extension's settings, select the _defined by theme_ option.
